import Header from "@/componets/header/header";
import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "@/componets/sidebar/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="main">
          <Sidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
